---
title: "PCA"
author: "Tamar Feldman"
date: '2023-05-08'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# IMPORT STATEMENTS

```{r include = FALSE}
library(DESeq2)
library(ggplot2)
```

# READ FILES

```{r}
my.col.file <-
  "../REFERENCE_FILES/DIFFERENTIAL_EXPRESSION/HumanColData_DESeq2_Input.csv"
my.col <- read.csv(file <- my.col.file, header = T, row.names = 1)

my.count.file <-
  "../PROCESSED_DATA/ALIGNMENT_RESULTS/HumanGeneCountsTable_v2.csv"
my.counts <-
  read.csv(file = my.count.file,
           header = T,
           row.names = 1)

# CHECK THAT COLUMN DATA AND COUNTS DATA ARE COMPATIBLE
all(rownames(my.col) %in% colnames(my.counts))
all(rownames(my.col) == colnames(my.counts))
```

## FUNCTION TO MAKE DDS

```{r}
my.conditions <- c("Media","SRS","Uninfected","Infected")
make.object <-
  function(filtered.coldata, filtered.counts, conditions){
    filtered.coldata$condition <- factor(filtered.coldata$condition, 
                                         levels = conditions)
    
    dds <- DESeqDataSetFromMatrix(countData = filtered.counts,
                                  colData = filtered.coldata,
                                  design = ~ condition)
    
    keep <- rowSums(counts(dds)>=10) >= 4 # LOW COUNT FILTER
    dds <- dds[keep,]
    return(dds)
}
```

## MAKE PCA ALL
```{r}
ntop <- 10000
my.dds <- make.object(my.col,my.counts,my.conditions)
my.vsd <- vst(my.dds)
rv <- rowVars(assay(my.vsd))
select <- order(rv, decreasing=TRUE)[seq_len(min(ntop, length(rv)))]

pca <- prcomp(t(assay(my.vsd)
                [select,]
                ))
PCA_RNA <-
  data.frame(
    PC1 = pca$x[, 1],
    PC2 = pca$x[, 2],
    PC3 = pca$x[, 3],
    CellType = my.col$cell.type,
    Condition = my.col$condition
  )

PCA_RNA$Condition <- factor(PCA_RNA$Condition,levels=c("Media","SRS","Uninfected","Infected"))
PCA_RNA$CellType <- factor(PCA_RNA$CellType, levels = c("ProE","BasoE","PolyE","OrthoE"))

PCA_summary <- summary(pca)
PC_sd <- setNames(PCA_summary$sdev[1:9], paste0("PC", 1:9))
PC_var_expl <- pca$sdev^2 / sum( pca$sdev^2 ) * 100
my.scree <- as.data.frame(PC_var_expl[1:9])
my.scree["PC"] <- row.names(my.scree)

p1 <- ggplot(PCA_RNA, aes(x = PC1, y = PC2)) +
  geom_point(
    aes(shape = CellType, fill = Condition),
    size = 5.75,
    alpha = 0.8,
    colour = "black"
  ) +
  #scale_color_manual(values = "black") + "#a6cee3"
  scale_fill_manual(values = c("#8da0cb", "#cb8dbe","#e5c494", "#a6d854")) +
  scale_shape_manual(values = c(22, 21, 24, 25)) +
  theme_bw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_blank(),
    panel.background = element_blank(),
    axis.line = element_line(colour = "black"),
    legend.position = "bottom",
    text = element_text(size = 18),
    axis.title = element_text(size = 18, family = "sans")
  ) +
  guides(
    fill = guide_legend(
      override.aes = list(shape = 23),
      nrow = 2,
      byrow = TRUE,
      title.position = "top",
      title = expression(underline("Condition")),
      title.theme = element_text(size = 18, family = "sans")
    ),
    shape = guide_legend(
      nrow = 2,
      byrow = TRUE,
      title.position = "top",
      title = expression(underline("Cell Type")),
      title.theme = element_text(size = 18, family = "sans")
    )
  ) +
  xlab(paste0("PC1: ", round(my.scree[1, 1], 1), "% variance")) +
  xlim(-100,175) +
  ylim(-60,90) +
  ylab(paste0("PC2: ", round(my.scree[2, 1], 1), "% variance")) +
  #scale_x_continuous(breaks = seq(-50,100,by = 50)) +
  #scale_y_continuous(breaks = seq(-60,60,by = 50)) 
  coord_equal(ratio=1)

 #+
  #geom_text_repel(aes(label = rownames(colData)))
ggsave(filename = "../PROCESSED_DATA/DESEQ2_RESULTS/PCA_All.svg",p1)
svg(
  "../PROCESSED_DATA/DESEQ2_RESULTS/PCA_All_13.svg",
  height = 6,
  width = 8
)
p1
dev.off()
```

## MAKE PCA FILTERED

```{r}
filter.coldata <-
  function(my.cell, coldata) {
    my.filter <- grepl(my.cell, row.names(coldata), fixed = FALSE)
    return(coldata[my.filter,])
  }

filter.counts <-
  function(my.cell, countdata){
    my.filter <- grepl(my.cell, colnames(countdata), fixed = FALSE)
    return(countdata[,my.filter])
  }

my.filtered.coldata <- filter.coldata("Media|Uninfected|Infected",my.col)
my.filtered.vsd <- filter.counts("Media|Uninfected|Infected",my.vsd)
```

```{r}
rv <- rowVars(assay(my.filtered.vsd))
select <- order(rv, decreasing=TRUE)[seq_len(min(ntop, length(rv)))]

pca <- prcomp(t(assay(my.filtered.vsd)
                [select,]
                ))
PCA_RNA <-
  data.frame(
    PC1 = pca$x[, 1],
    PC2 = pca$x[, 2],
    PC3 = pca$x[, 3],
    CellType = my.filtered.coldata$cell.type,
    Condition = my.filtered.coldata$condition
  )

PCA_RNA$Condition <- factor(PCA_RNA$Condition,levels=c("Media","Uninfected","Infected"))
PCA_RNA$CellType <- factor(PCA_RNA$CellType, levels = c("ProE","BasoE","PolyE","OrthoE"))

PCA_summary <- summary(pca)
PC_sd <- setNames(PCA_summary$sdev[1:9], paste0("PC", 1:9))
PC_var_expl <- pca$sdev^2 / sum( pca$sdev^2 ) * 100
my.scree <- as.data.frame(PC_var_expl[1:9])
my.scree["PC"] <- row.names(my.scree)
```

```{r}
p1 <- ggplot(PCA_RNA, aes(x = PC1, y = PC3)) +
  geom_point(
    aes(shape = CellType, fill = Condition),
    size = 5.75,
    alpha = 0.8,
    colour = "black"
  ) +
  #scale_color_manual(values = "black") + "#a6cee3"
  scale_fill_manual(values = c("#8da0cb", "#e5c494", "#a6d854")) +
  scale_shape_manual(values = c(22, 21, 24, 25)) +
  theme_bw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_blank(),
    panel.background = element_blank(),
    axis.line = element_line(colour = "black"),
    legend.position = "bottom",
    text = element_text(size = 18),
    axis.title = element_text(size = 18, family = "sans")
  ) +
  guides(
    fill = guide_legend(
      override.aes = list(shape = 23),
      nrow = 2,
      byrow = TRUE,
      title.position = "top",
      title = expression(underline("Condition")),
      title.theme = element_text(size = 18, family = "sans")
    ),
    shape = guide_legend(
      nrow = 2,
      byrow = TRUE,
      title.position = "top",
      title = expression(underline("Cell Type")),
      title.theme = element_text(size = 18, family = "sans")
    )
  ) +
  xlab(paste0("PC1: ", round(my.scree[1, 1], 1), "% variance")) +
  xlim(-100,175) +
  ylim(-70,60) +
  ylab(paste0("PC3: ", round(my.scree[3, 1], 1), "% variance")) +
  #scale_x_continuous(breaks = seq(-50,100,by = 50)) +
  #scale_y_continuous(breaks = seq(-60,60,by = 50)) 
  coord_equal(ratio=1)

 #+
  #geom_text_repel(aes(label = rownames(colData)))
ggsave(filename = "../PROCESSED_DATA/DESEQ2_RESULTS/PCA_filtered_13.svg",p1)
```

```{r}
svg(
  "../PROCESSED_DATA/DESEQ2_RESULTS/PCA_filtered.svg",
  height = 6,
  width = 8
)
p1
dev.off()
```

